$(function(){"use strict";function isotope_filter(){var $container=$('.isotope').isotope({itemSelector:'.grid-item ,.blog-item',getSortData:{}});$('.portfolio-filter').on('click','li a',function(){$(this).parent().addClass('active').siblings().removeClass('active');var filterValue=$(this).attr('data-filter');$container.isotope({filter:filterValue})})}
function scrollfix(){var scroll=$(window).scrollTop();if(scroll>0){$(".home2 #header").css({"background":"rgba(0,0,0,0.9)"})}
else{$(".home2 #header").css({"background":"rgba(0,0,0,0)"})}}
function bannerheight(){var bannerheight=$(".banner").height();$(".banner-detail").css('top',Math.round(bannerheight/2)+'px');var banner2height=$(".banner2").height();$(".banner-detail,.fnc-slide__content").css('top',Math.round(banner2height/2.5)+'px');var full_onescreen_banner_height=$("#container").height();$(".banner-detail").css('top',Math.round(full_onescreen_banner_height/3)+'px')}
function re_size(){if($(window).width()<=991){$('.nav li').on('click',function(){$('.#menu ul').css({"display":"none"})});$('.cd-intro').children('button').removeClass('mt_30').addClass('mt_20')}
if($(window).width()>991){$('.cd-intro').children('button').addClass('mt_30').removeClass('mt_20')}}
function m_popup_select(){$('.grid').magnificPopup({delegate:'a',type:'image',closeOnContentClick:!1,closeBtnInside:!1,mainClass:'mfp-with-zoom mfp-img-mobile',image:{verticalFit:!0,},gallery:{enabled:!0},zoom:{enabled:!0,duration:300,opener:function(element){return element.find('img')}}})}
function owl_carousel(){$('.client').owlCarousel({loop:!0,autoplay:!0,responsiveClass:!0,items:1,responsive:{0:{items:1,nav:!1},600:{items:1,nav:!0},1000:{items:1,nav:!0,loop:!0}}})
$('#blog-post').owlCarousel({loop:!1,autoplay:!1,responsiveClass:!0,items:3,responsive:{0:{items:1,nav:!1},600:{items:2,nav:!1},1000:{items:3,nav:!0,loop:!0}}})
$('.team3col').owlCarousel({autoplay:!1,responsiveClass:!0,items:3,responsive:{0:{items:1,nav:!1},600:{items:2,nav:!0},1000:{items:3,nav:!0,}}})}
function colorswitcher(){$(".style1").click(function(){$("#colors").attr("href","css/color/style1.css");return!1});$(".style2").click(function(){$("#colors").attr("href","css/color/style2.css");return!1});$(".style3").click(function(){$("#colors").attr("href","css/color/style3.css");return!1});$(".style4").click(function(){$("#colors").attr("href","css/color/style4.css");return!1});$(".style5").click(function(){$("#colors").attr("href","css/color/style5.css");return!1});$(".style6").click(function(){$("#colors").attr("href","css/color/style6.css");return!1});$(".style7").click(function(){$("#colors").attr("href","css/color/style7.css");return!1});$(".style8").click(function(){$("#colors").attr("href","css/color/style8.css");return!1});$(".style9").click(function(){$("#colors").attr("href","css/color/style9.css");return!1});$(".style10").click(function(){$("#colors").attr("href","css/color/style10.css");return!1});$(".style11").click(function(){$("#colors").attr("href","css/color/style11.css");return!1});$(".style12").click(function(){$("#colors").attr("href","css/color/style12.css");return!1});$(".style13").click(function(){$("#colors").attr("href","css/color/style13.css");return!1});$(".style14").click(function(){$("#colors").attr("href","css/color/style14.css");return!1});$(".style15").click(function(){$("#colors").attr("href","css/color/style15.css");return!1});$(".style16").click(function(){$("#colors").attr("href","css/color/style16.css");return!1});$(".style17").click(function(){$("#colors").attr("href","css/color/style17.css");return!1});$(".style18").click(function(){$("#colors").attr("href","css/color/style18.css");return!1});$(".style19").click(function(){$("#colors").attr("href","css/color/style19.css");return!1});$(".style20").click(function(){$("#colors").attr("href","css/color/style20.css");return!1});$('#colors-switcher').animate({left:'-160px'});$('#colors-switcher h2 a').click(function(e){e.preventDefault();var div=$('#colors-switcher');console.log(div.css('left'));if(div.css('left')==='-160px'){$('#colors-switcher').animate({left:'0px'})}else{$('#colors-switcher').animate({left:'-160px'})}});$('.colors li a').click(function(e){e.preventDefault();$(this).parent().parent().find('a').removeClass('active');$(this).addClass('active')})}
function parallax(){var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent);if(!isMobile){if($(".parallax").length){$(".parallax").sitManParallex({invert:!1})}}else{$(".parallax").sitManParallex({invert:!0})}}
$(window).on("load",function(){isotope_filter();bannerheight()});$(window).ready(function(){$('[data-toggle="tooltip"]').tooltip();$(".loder").fadeOut("slow");scrollfix();owl_carousel();bannerheight();re_size();colorswitcher();parallax();isotope_filter()});$(window).resize(function(){re_size();bannerheight()});$(window).scroll(function(){scrollfix()});$(document).ready(function(){m_popup_select()})})